// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace challenge_metafar.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240327184735_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.CuentaBancaria", b =>
                {
                    b.Property<int>("IDCuentaBancaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDCuentaBancaria"));

                    b.Property<int>("NroCuenta")
                        .HasColumnType("int");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("IDCuentaBancaria");

                    b.ToTable("CuentaBancaria");
                });

            modelBuilder.Entity("Domain.Models.Movimiento", b =>
                {
                    b.Property<int>("IDMovimientos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDMovimientos"));

                    b.Property<int>("CuentaBancariaIDCuentaBancaria")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDCuentaBancaria")
                        .HasColumnType("int");

                    b.Property<int?>("TarjetaIDTarjeta")
                        .HasColumnType("int");

                    b.HasKey("IDMovimientos");

                    b.HasIndex("CuentaBancariaIDCuentaBancaria");

                    b.HasIndex("TarjetaIDTarjeta");

                    b.ToTable("Movimiento");
                });

            modelBuilder.Entity("Domain.Models.Tarjeta", b =>
                {
                    b.Property<int>("IDTarjeta")
                        .HasColumnType("int")
                        .HasColumnName("IDTarjeta");

                    b.Property<int>("Intentos")
                        .HasColumnType("int");

                    b.Property<string>("NroTarjeta")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<int>("Pin")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("Pin");

                    b.Property<bool>("TarjetaBloqueada")
                        .HasColumnType("bit");

                    b.HasKey("IDTarjeta");

                    b.ToTable("Tarjetas", (string)null);
                });

            modelBuilder.Entity("Domain.Models.TipoMovimiento", b =>
                {
                    b.Property<int>("IDTipoMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDTipoMovimiento"));

                    b.Property<string>("DescripcionMovimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovimientoIDMovimientos")
                        .HasColumnType("int");

                    b.HasKey("IDTipoMovimiento");

                    b.HasIndex("MovimientoIDMovimientos");

                    b.ToTable("TipoMovimiento");
                });

            modelBuilder.Entity("Domain.Models.Usuario", b =>
                {
                    b.Property<int>("IDUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUsuario"));

                    b.Property<int>("CuentaBancariaIDCuentaBancaria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDUsuario");

                    b.HasIndex("CuentaBancariaIDCuentaBancaria");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Domain.Models.Movimiento", b =>
                {
                    b.HasOne("Domain.Models.CuentaBancaria", "CuentaBancaria")
                        .WithMany("Movimientos")
                        .HasForeignKey("CuentaBancariaIDCuentaBancaria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Tarjeta", null)
                        .WithMany("Movimientos")
                        .HasForeignKey("TarjetaIDTarjeta");

                    b.Navigation("CuentaBancaria");
                });

            modelBuilder.Entity("Domain.Models.Tarjeta", b =>
                {
                    b.HasOne("Domain.Models.CuentaBancaria", "CuentaBancaria")
                        .WithOne("Tarjeta")
                        .HasForeignKey("Domain.Models.Tarjeta", "IDTarjeta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuentaBancaria");
                });

            modelBuilder.Entity("Domain.Models.TipoMovimiento", b =>
                {
                    b.HasOne("Domain.Models.Movimiento", "Movimiento")
                        .WithMany("TipoMovimiento")
                        .HasForeignKey("MovimientoIDMovimientos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movimiento");
                });

            modelBuilder.Entity("Domain.Models.Usuario", b =>
                {
                    b.HasOne("Domain.Models.CuentaBancaria", "CuentaBancaria")
                        .WithMany("Usuario")
                        .HasForeignKey("CuentaBancariaIDCuentaBancaria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuentaBancaria");
                });

            modelBuilder.Entity("Domain.Models.CuentaBancaria", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("Tarjeta")
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Models.Movimiento", b =>
                {
                    b.Navigation("TipoMovimiento");
                });

            modelBuilder.Entity("Domain.Models.Tarjeta", b =>
                {
                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
